services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: P10PatientDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  patientMicroservice:
    build:
      context: .
      dockerfile: ./PatientMicroservice/Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "60996:8080"
    depends_on:
      - postgres
    
  mongoDB:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  notesMicroservice:
    build:
      context: .
      dockerfile: ./NotesMicroservice/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "60997:8080"
    depends_on:
      - mongoDB

  reportMicroservice:
    build:
      context: .
      dockerfile: ./ReportMicroservice/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "60998:8080"

volumes:
  postgres_data:
  mongodb_data: